### ISSUE TITLE
Seems to not work with packages that have a dash (-) in the name.. Seems to have been a problem with the cache..

### ISSUE THREAD

**Issue by abchk1234** [cwilling/hoorex#12]
Examples:

```
$ ./hoorex -r ttf-mscorefonts -d
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /home/aaditya/slackbuilds from config file
DEBUG: sbo_path: /home/aaditya/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: []
DEBUG: REVERSE mode set at command line
DEBUG: [[]]
```

```
$ ./hoorex -r cantarell-fonts -d
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /home/aaditya/slackbuilds from config file
DEBUG: sbo_path: /home/aaditya/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: []
DEBUG: REVERSE mode set at command line
DEBUG: [[]]
```

Tried with `0.5.6` as well as git version.

**Comment by cwilling** [comment]
I'm not sure why its like that for you. Using the same commands, I see:
chris@d6:~$ hoorex -r ttf-mscorefonts -d
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /scratch/PKG/SBo/slackbuilds from config file
DEBUG: sbo_path: /scratch/PKG/SBo/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: ['ttf-mscorefonts']
DEBUG: REVERSE mode set at command line
DEBUG: [['ttf-mscorefonts'], ['cabextract']]
DEBUG: Moving cabextract to sorted queue
DEBUG: Moving ttf-mscorefonts to sorted queue
cabextract ttf-mscorefonts 
chris@d6:~$ hoorex -r cantarell-fonts -d
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /scratch/PKG/SBo/slackbuilds from config file
DEBUG: sbo_path: /scratch/PKG/SBo/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: ['cantarell-fonts']
DEBUG: REVERSE mode set at command line
DEBUG: [['cantarell-fonts'], []]
DEBUG: Moving cantarell-fonts to sorted queue
cantarell-fonts 
chris@d6:~$

Your result is definitely strange - notice the line "Processing initial targets of: []" as if its not seeing the target package name. If you have some time for some extra testing, could you find  line 81 in hoorex that says: 'args = parser.parse_args()'; then immediately after that line, add a new line saying 'print(args)'? That will print out whatever hoorex thinks has been passed from the command line. In that case, I see:
chris@d6:~/src/hoorex$ ./hoorex -r ttf-mscorefonts -d
Namespace(app_version=False, debug_mode=True, force=False, multilevel=False, output_column=False, output_installed=False, output_long=False, output_strictly_installed=False, reverse_lookup=True, sbo_group=None, sbo_path=None, target=['ttf-mscorefonts'], unknown_strict=False)
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /scratch/PKG/SBo/slackbuilds from config file
DEBUG: sbo_path: /scratch/PKG/SBo/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: ['ttf-mscorefonts']
DEBUG: REVERSE mode set at command line
DEBUG: [['ttf-mscorefonts'], ['cabextract']]
DEBUG: Moving cabextract to sorted queue
DEBUG: Moving ttf-mscorefonts to sorted queue
cabextract ttf-mscorefonts 
chris@d6:~/src/hoorex$

Notice that the extra output includes "target=['ttf-mscorefonts']". Does your new output have that?

**Comment by abchk1234** [comment]
Yup, it seems to have that:

$ ./hoorex -r ttf-mscorefonts -d
Namespace(app_version=False, debug_mode=True, force=False, multilevel=False, output_column=False, output_installed=False, output_long=False, output_strictly_installed=False, reverse_lookup=True, sbo_group=None, sbo_path=None, target=['ttf-mscorefonts'], unknown_strict=False)
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /home/aaditya/slackbuilds from config file
DEBUG: sbo_path: /home/aaditya/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: []
DEBUG: REVERSE mode set at command line
DEBUG: [[]]

Some more examples:

```
$ ./hoorex -r hoorex -d
Namespace(app_version=False, debug_mode=True, force=False, multilevel=False, output_column=False, output_installed=False, output_long=False, output_strictly_installed=False, reverse_lookup=True, sbo_group=None, sbo_path=None, target=['hoorex'], unknown_strict=False)
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /home/aaditya/slackbuilds from config file
DEBUG: sbo_path: /home/aaditya/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: []
DEBUG: REVERSE mode set at command line
DEBUG: [[]]
```

```
 $ ./hoorex -r wine -d
Namespace(app_version=False, debug_mode=True, force=False, multilevel=False, output_column=False, output_installed=False, output_long=False, output_strictly_installed=False, reverse_lookup=True, sbo_group=None, sbo_path=None, target=['wine'], unknown_strict=False)
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /home/aaditya/slackbuilds from config file
DEBUG: sbo_path: /home/aaditya/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: ['wine']
DEBUG: REVERSE mode set at command line
DEBUG: [['wine'], ['fontforge', 'webcore-fonts']]
DEBUG: Moving fontforge to sorted queue
DEBUG: webcore-fonts still needed (in wine)
DEBUG: Moving webcore-fonts to sorted queue
DEBUG: Moving wine to sorted queue
fontforge webcore-fonts wine 
```

```
$ ./hoorex -r dosbox -d
Namespace(app_version=False, debug_mode=True, force=False, multilevel=False, output_column=False, output_installed=False, output_long=False, output_strictly_installed=False, reverse_lookup=True, sbo_group=None, sbo_path=None, target=['dosbox'], unknown_strict=False)
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /home/aaditya/slackbuilds from config file
DEBUG: sbo_path: /home/aaditya/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: ['dosbox']
DEBUG: REVERSE mode set at command line
DEBUG: [['dosbox'], []]
DEBUG: Moving dosbox to sorted queue
dosbox 
```

Dont know why it is not working with some packages...

**Comment by abchk1234** [comment]
Removing `.local/share/hoorex/repoData.pkl` seems to have fixed the issue.

```
$ ./hoorex -r ttf-mscorefonts -d
Namespace(app_version=False, debug_mode=True, force=False, multilevel=False, output_column=False, output_installed=False, output_long=False, output_strictly_installed=False, reverse_lookup=True, sbo_group=None, sbo_path=None, target=['ttf-mscorefonts'], unknown_strict=False)
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /home/aaditya/slackbuilds from config file
DEBUG: sbo_path: /home/aaditya/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: ['ttf-mscorefonts']
DEBUG: REVERSE mode set at command line
DEBUG: [['ttf-mscorefonts'], ['cabextract']]
DEBUG: Moving cabextract to sorted queue
DEBUG: Moving ttf-mscorefonts to sorted queue
cabextract ttf-mscorefonts 
```

```
$ ./hoorex -r hoorex -d
Namespace(app_version=False, debug_mode=True, force=False, multilevel=False, output_column=False, output_installed=False, output_long=False, output_strictly_installed=False, reverse_lookup=True, sbo_group=None, sbo_path=None, target=['hoorex'], unknown_strict=False)
DEBUG: VERBOSE mode set at command line
DEBUG: Set sbo_path to /home/aaditya/slackbuilds from config file
DEBUG: sbo_path: /home/aaditya/slackbuilds
DEBUG: Loading existing repo data
DEBUG: PkgData loaded from file OK
DEBUG: Processing initial targets of: ['hoorex']
DEBUG: REVERSE mode set at command line
DEBUG: [['hoorex'], []]
DEBUG: Moving hoorex to sorted queue
hoorex 
```

**Comment by cwilling** [comment]
Interesting. After removing the repoData.pkl file, a new one would be generated when you run the next hoorex command. Since it now works OK, the old one must have been faulty/corrupted somehow.

BTW when you say you removed the .local/share/hoorex/repoData.pkl, I assume you meant ~/.local/hoorex/share/repoData.pkl did you i.e. relative to the user's home directory?

**Comment by abchk1234** [comment]
Yes on both counts, a new one was generated, and I meant relative to home directory.
