### ISSUE TITLE
Output to file

### ISSUE THREAD

**Issue by cwilling** [cwilling/hoorex#5]
Do we need  a "write to file" option? Its easy enough to redirect stdout without a dedicated option.

**Comment by jvvv** [comment]
Redirecting stdout works well enough for me. If I'm getting a long list for more than one package's deps, I usually filter through sort and uniq anyways.

**Comment by cwilling** [comment]
Thanks for the feedback jvvv. I was thinking redirection should be enough - just looking for someone to agree.

About filtering output, using uniq shouldn't be necessary - its already done internally.

**Comment by jvvv** [comment]
On Wed, 06 May 2015 06:49:30 -0700
cwilling notifications@github.com wrote:

> Thanks for the feedback jvvv. I was thinking redirection should be enough - just looking for someone to agree.
> 
> About filtering output, using uniq shouldn't be necessary - its already done internally.

Thanks for that. Bit of a habit of mine to do it that way. I appreciate the heads up. Also, thank you for the
excellent tool.

**Comment by cwilling** [comment]
Since there's no screaming demand for this one, I'll drop the idea and close the issue.
